package stellamagicamod.core;

import c6h2cl2.YukariLib.Util.RegisterHandler
import cpw.mods.fml.common.Mod
import cpw.mods.fml.common.ModMetadata
import cpw.mods.fml.common.event.FMLInitializationEvent
import cpw.mods.fml.common.event.FMLPreInitializationEvent

@Mod(modid = StellaMagicaModCore.MOD_ID, name = StellaMagicaModCore.MOD_NAME, useMetadata = true, dependencies = "required-after:Forge@[10.13.4.1558,);required-after:YukariLib")
class StellaMagicaModCore {
    companion object {
        const val MOD_ID = "StellaMagicaMod"
        const val MOD_NAME = "StellaMagicaMod Core"
        const val MOD_VERSION = "1.0.0"
        @Mod.Metadata
        var meta: ModMetadata? = null
        @Mod.Instance(MOD_ID)
        var INSTANCE: StellaMagicaModCore? = null
    }

    @Mod.EventHandler
    fun preinit(event: FMLPreInitializationEvent) {
        RegisterHandler().build(SMMRegistry).handle()
        SMMRegistry.handleInit()
    }

    @Mod.EventHandler
    fun init(event: FMLInitializationEvent) {
        SMMRegistry.handleInit()
    }

    fun loadMeta() {
        val meta = meta as ModMetadata
        meta.modId = MOD_ID
        meta.name = MOD_NAME
        meta.version = MOD_VERSION
        meta.authorList.add("Asphere103")
        meta.description = "Make StellaMagica in Minecraft!"
        meta.autogenerated = false
    }
}